Andrej Gorjup -> [Andrej Gorjup, Cvetka Ertl: Prvi clanek (2016), Franc Bizjak, Andrej Gorjup, Borut Fink: Drugi clanek (2015)]
Borut Fink -> [Gabrijela Arko, Borut Fink: Tretji clanek (2016), Borut Fink, Ema Cevc: Cetrti clanek (2015), Franc Bizjak, Andrej Gorjup, Borut Fink: Drugi clanek (2015)]
Cvetka Ertl -> [Andrej Gorjup, Cvetka Ertl: Prvi clanek (2016), Ema Cevc, Cvetka Ertl, Franc Bizjak: Peti clanek (2015)]
Ema Cevc -> [Ema Cevc: Sesti clanek (2016), Borut Fink, Ema Cevc: Cetrti clanek (2015), Ema Cevc, Cvetka Ertl, Franc Bizjak: Peti clanek (2015)]
Franc Bizjak -> [Franc Bizjak, Andrej Gorjup, Borut Fink: Drugi clanek (2015), Ema Cevc, Cvetka Ertl, Franc Bizjak: Peti clanek (2015)]
Gabrijela Arko -> [Gabrijela Arko, Borut Fink: Tretji clanek (2016)]
