Janez Novak, Eva Novak: Vpliv nogometa na rast delnic (2019)
Janez Novak, Eva Novak: Vpliv cene zelenjave na rast delnic (2018)
Eva Novak: Vpliv nogometa na cene zelenjave (2018)
Janez Novak, Janez Novak: Vpliv nogometa na vreme (2017)
Janez Novak, Eva Novak: Vpliv rasti delnic na vreme (2017)
Mojca Novak, Eva Medved, Olga Zajc: Vpliv cene zelenjave na vreme (2016)
Brigita Pirc, Eva Medved, Olga Zajc: Vpliv vremena na rast delnic (2016)
Janez Novak, Eva Medved, Eva Novak, Olga Zajc: Vpliv vremena na cene zelenjave (2015)
Brigita Pirc, Janez Novak, Mojca Novak: Vpliv vremena na nogomet (2015)
Janez Novak, Eva Novak: Vpliv vremena na rast delnic (2015)
