Ana Cotman -> [Ana Cotman, Draga Leban: ababa (2005), Cvetko Kotnik, Ana Cotman: abbbb (2000)]
Ana Cotman -> [Karel Leban, Ana Cotman: bbbaa (2007)]
Ana Ermenc -> [Ana Ermenc, Olga Hojnik, Zoran Novak: abbba (2002)]
Ana Fajdiga -> [Ana Fajdiga, Iva Bevc: bbbbb (2011)]
Ana Golob -> [Ana Golob, Tone Jelen: bbbaa (2005)]
Ana Hojnik -> [Ana Hojnik: bbbab (2013)]
Ana Ilih -> [Zoran Leban, Ana Ilih, Bojan Ilih: aabab (2019), Sonja Bevc, Ana Ilih, Hinko Oblak: baaba (2014)]
Ana Jelen -> [Veronika Hojnik, Ana Zorc, Ana Jelen: aaaba (2015)]
Ana Novak -> [Ana Zorc, Ana Novak, Eva Ilih: bbbba (2008)]
Ana Oblak -> [Ana Oblak: abaaa (2007)]
Ana Tratnik -> [Ana Tratnik, Mateja Ilih, Iva Rant: aabbb (2015), Ana Tratnik: baaaa (2015), Ana Tratnik, Eva Cotman, Nina Leban: bbbaa (2007)]
Ana Veble -> [Ana Veble: bbaab (2012)]
Ana Veble -> [Urban Podobnik, Nina Debeljak, Ana Veble: bbbaa (2005)]
Ana Zorc -> [Veronika Hojnik, Ana Zorc, Ana Jelen: aaaba (2015), Ana Zorc, Ana Novak, Eva Ilih: bbbba (2008), Veronika Debeljak, Ana Zorc: ababa (2003), Ana Zorc, Eva Golob, Veronika Fajdiga: babaa (2002)]
Bojan Cotman -> [Bojan Cotman, Jana Ilih, Hinko Zorc: aaaba (2016), Jana Rant, Bojan Cotman: bbbab (2008)]
Bojan Ilih -> [Zoran Leban, Ana Ilih, Bojan Ilih: aabab (2019)]
Bojan Leban -> [Bojan Leban, Hinko Veble, Veronika Zorc: abaab (2007)]
Bojan Novak -> [Bojan Novak: abbaa (2006)]
Bojan Novak -> [Tone Fajdiga, Bojan Novak, Urban Bevc: abbaa (2012), Bojan Novak, Cvetko Savc, Eva Antlej: aabab (2009)]
Bojan Podobnik -> [Franci Fajdiga, Draga Podobnik, Bojan Podobnik: bbbbb (2000)]
Bojan Podobnik -> [Peter Hojnik, Cvetko Mastnak, Bojan Podobnik: abbaa (2011)]
Bojan Savc -> [Bojan Savc: aabbb (2009)]
Bojan Tratnik -> [Urban Ilih, Bojan Tratnik, Roman Oblak: babba (2002)]
Bojan Urh -> [Bojan Urh, Bojan Veble: baaba (2001)]
Bojan Urh -> [Bojan Urh, Gorazd Podobnik, Tone Bevc: abbbb (2018)]
Bojan Veble -> [Bojan Urh, Bojan Veble: baaba (2001), Veronika Novak, Bojan Veble: baaba (2000)]
Bojan Zorc -> [Bojan Zorc: aabaa (2016)]
Cvetko Antlej -> [Cvetko Antlej, Eva Bevc, Jana Zorc: aaabb (2000)]
Cvetko Kotnik -> [Cvetko Kotnik, Ana Cotman: abbbb (2000)]
Cvetko Kotnik -> [Roman Urh, Lojze Antlej, Cvetko Kotnik: babba (2019)]
Cvetko Leban -> [Cvetko Leban, Tone Jelen: aaabb (2007)]
Cvetko Mastnak -> [Peter Hojnik, Cvetko Mastnak, Bojan Podobnik: abbaa (2011), Sonja Urh, Zoran Novak, Cvetko Mastnak: baaba (2010)]
Cvetko Novak -> [Lojze Zorc, Gorazd Hojnik, Cvetko Novak: abaaa (2005)]
Cvetko Oblak -> [Cvetko Oblak: baaaa (2001)]
Cvetko Rant -> [Cvetko Rant: baaba (2004)]
Cvetko Rant -> [Peter Golob, Eva Ilih, Cvetko Rant: bbbbb (2003)]
Cvetko Rant -> [Peter Leban, Cvetko Rant: babba (2000)]
Cvetko Savc -> [Bojan Novak, Cvetko Savc, Eva Antlej: aabab (2009)]
Cvetko Tratnik -> [Cvetko Tratnik, Eva Mastnak: abbab (2016), Cvetko Tratnik: babab (2011)]
Cvetko Tratnik -> [Tone Veble, Eva Golob, Cvetko Tratnik: aabab (2014), Mateja Bevc, Cvetko Tratnik, Zoran Fajdiga: babaa (2012)]
Cvetko Veble -> [Jana Veble, Lojze Zorc, Cvetko Veble: abbbb (2002)]
Cvetko Zorc -> [Cvetko Zorc, Jana Leban, Eva Fajdiga: baaba (2009)]
Draga Ermenc -> [Draga Ermenc: bbaab (2010)]
Draga Fajdiga -> [Draga Fajdiga, Roman Leban, Eva Kotnik: aaaab (2005), Draga Fajdiga: bbaaa (2000)]
Draga Golob -> [Hinko Rant, Draga Golob, Eva Oblak: bbaaa (2017)]
Draga Golob -> [Mateja Ilih, Draga Golob: baaaa (2007)]
Draga Leban -> [Ana Cotman, Draga Leban: ababa (2005), Zoran Debeljak, Draga Leban: bbbba (2003)]
Draga Podobnik -> [Franci Fajdiga, Draga Podobnik, Bojan Podobnik: bbbbb (2000)]
Draga Savc -> [Nina Hojnik, Draga Savc: bbbba (2013)]
Draga Veble -> [Draga Veble, Eva Leban: aabab (2014)]
Draga Zorc -> [Draga Zorc: aabba (2010), Draga Zorc: abbbb (2010)]
Eva Antlej -> [Bojan Novak, Cvetko Savc, Eva Antlej: aabab (2009), Eva Antlej, Hinko Veble: aabab (2001)]
Eva Bevc -> [Eva Bevc, Franci Fajdiga: abbbb (2010), Cvetko Antlej, Eva Bevc, Jana Zorc: aaabb (2000)]
Eva Bevc -> [Eva Bevc, Nina Debeljak: bbabb (2010)]
Eva Cotman -> [Ana Tratnik, Eva Cotman, Nina Leban: bbbaa (2007)]
Eva Fajdiga -> [Cvetko Zorc, Jana Leban, Eva Fajdiga: baaba (2009)]
Eva Golob -> [Ana Zorc, Eva Golob, Veronika Fajdiga: babaa (2002)]
Eva Golob -> [Karel Savc, Eva Golob: aabab (2010)]
Eva Golob -> [Tone Veble, Eva Golob, Cvetko Tratnik: aabab (2014), Eva Golob: aabbb (2014)]
Eva Ilih -> [Ana Zorc, Ana Novak, Eva Ilih: bbbba (2008), Peter Golob, Eva Ilih, Cvetko Rant: bbbbb (2003)]
Eva Ilih -> [Eva Ilih: bbaaa (2002)]
Eva Kotnik -> [Draga Fajdiga, Roman Leban, Eva Kotnik: aaaab (2005)]
Eva Leban -> [Franci Zorc, Lojze Rant, Eva Leban: baaaa (2019), Draga Veble, Eva Leban: aabab (2014)]
Eva Mastnak -> [Cvetko Tratnik, Eva Mastnak: abbab (2016)]
Eva Novak -> [Eva Novak, Nina Zorc: abaab (2014)]
Eva Novak -> [Peter Hojnik, Eva Novak: baabb (2019), Eva Novak, Nina Hojnik: bbaaa (2018)]
Eva Oblak -> [Hinko Rant, Draga Golob, Eva Oblak: bbaaa (2017), Roman Urh, Eva Oblak, Tone Tratnik: aabbb (2016), Eva Oblak, Peter Zorc, Olga Ilih: babab (2004)]
Eva Podobnik -> [Eva Podobnik: abaab (2018), Eva Podobnik: abbaa (2018)]
Eva Veble -> [Eva Veble: abbbb (2014)]
Eva Veble -> [Zoran Kotnik, Eva Veble: aabba (2009)]
Eva Zorc -> [Eva Zorc: abaaa (2010)]
Franci Bevc -> [Franci Golob, Franci Bevc: babba (2008), Franci Bevc, Tone Savc: ababb (2006), Franci Bevc: babbb (2006)]
Franci Bevc -> [Veronika Novak, Tone Mastnak, Franci Bevc: abaaa (2005)]
Franci Debeljak -> [Gorazd Savc, Franci Debeljak: aabab (2010)]
Franci Debeljak -> [Mateja Ilih, Franci Debeljak, Olga Veble: babab (2011)]
Franci Ermenc -> [Franci Ermenc, Nina Tratnik, Olga Jelen: abbbb (2001)]
Franci Ermenc -> [Zoran Veble, Franci Ermenc: ababb (2005)]
Franci Fajdiga -> [Eva Bevc, Franci Fajdiga: abbbb (2010), Franci Fajdiga, Draga Podobnik, Bojan Podobnik: bbbbb (2000)]
Franci Golob -> [Franci Golob, Franci Bevc: babba (2008), Franci Golob, Franci Tratnik: bbaab (2000)]
Franci Hojnik -> [Mateja Leban, Franci Hojnik, Peter Veble: bbbaa (2001)]
Franci Leban -> [Franci Leban, Olga Novak: aabab (2009)]
Franci Rant -> [Jana Antlej, Sonja Debeljak, Franci Rant: babab (2010)]
Franci Tratnik -> [Iva Jelen, Franci Tratnik: bbaba (2003), Franci Golob, Franci Tratnik: bbaab (2000)]
Franci Zorc -> [Franci Zorc, Lojze Rant, Eva Leban: baaaa (2019)]
Gorazd Antlej -> [Gorazd Antlej: bbbaa (2012), Gorazd Oblak, Gorazd Antlej, Olga Ilih: aabba (2011), Gorazd Antlej, Peter Zorc, Karel Golob: baaba (2010)]
Gorazd Fajdiga -> [Gorazd Fajdiga, Veronika Kotnik: bbaba (2004)]
Gorazd Golob -> [Gorazd Golob, Tone Tratnik: bbbab (2012), Gorazd Golob, Jana Antlej, Peter Golob: aaaba (2004)]
Gorazd Hojnik -> [Gorazd Hojnik: bbbaa (2015)]
Gorazd Hojnik -> [Lojze Zorc, Gorazd Hojnik, Cvetko Novak: abaaa (2005)]
Gorazd Novak -> [Roman Leban, Gorazd Novak: bbabb (2015), Tone Podobnik, Gorazd Novak: aaabb (2006)]
Gorazd Oblak -> [Gorazd Oblak, Karel Leban, Lojze Zorc: baaaa (2012)]
Gorazd Oblak -> [Gorazd Oblak: bbabb (2017), Gorazd Oblak, Gorazd Antlej, Olga Ilih: aabba (2011), Urban Leban, Gorazd Oblak, Zoran Mastnak: aabab (2005), Hinko Debeljak, Gorazd Oblak, Sonja Savc: babaa (2005)]
Gorazd Podobnik -> [Bojan Urh, Gorazd Podobnik, Tone Bevc: abbbb (2018), Sonja Bevc, Gorazd Podobnik, Olga Veble: bbaaa (2001)]
Gorazd Podobnik -> [Gorazd Podobnik, Sonja Zorc: abbaa (2014)]
Gorazd Savc -> [Gorazd Savc, Franci Debeljak: aabab (2010)]
Gorazd Savc -> [Gorazd Savc, Nina Novak, Veronika Novak: bbaab (2011), Jana Urh, Gorazd Savc, Jana Ermenc: abbbb (2007)]
Gorazd Tratnik -> [Gorazd Tratnik, Urban Podobnik, Zoran Fajdiga: baaba (2014)]
Gorazd Urh -> [Roman Leban, Gorazd Urh, Sonja Veble: abbab (2003)]
Hinko Debeljak -> [Zoran Golob, Hinko Debeljak: bbaba (2018), Hinko Debeljak, Gorazd Oblak, Sonja Savc: babaa (2005)]
Hinko Golob -> [Olga Novak, Hinko Golob: baabb (2003)]
Hinko Kotnik -> [Hinko Kotnik, Hinko Leban, Zoran Fajdiga: baabb (2010)]
Hinko Kotnik -> [Hinko Kotnik, Jana Rant: babaa (2015)]
Hinko Leban -> [Hinko Kotnik, Hinko Leban, Zoran Fajdiga: baabb (2010)]
Hinko Oblak -> [Sonja Bevc, Ana Ilih, Hinko Oblak: baaba (2014)]
Hinko Rant -> [Hinko Rant, Draga Golob, Eva Oblak: bbaaa (2017)]
Hinko Rant -> [Hinko Rant: bbbaa (2002)]
Hinko Savc -> [Peter Veble, Tone Podobnik, Hinko Savc: abbba (2005)]
Hinko Veble -> [Bojan Leban, Hinko Veble, Veronika Zorc: abaab (2007), Eva Antlej, Hinko Veble: aabab (2001)]
Hinko Veble -> [Hinko Veble, Roman Urh, Lojze Rant: abbba (2015)]
Hinko Zorc -> [Bojan Cotman, Jana Ilih, Hinko Zorc: aaaba (2016)]
Hinko Zorc -> [Veronika Zorc, Sonja Veble, Hinko Zorc: bbaba (2016)]
Iva Bevc -> [Ana Fajdiga, Iva Bevc: bbbbb (2011), Karel Debeljak, Iva Bevc: bbabb (2000)]
Iva Jelen -> [Iva Jelen: aaaaa (2005)]
Iva Jelen -> [Iva Jelen: bbbaa (2009), Iva Jelen, Franci Tratnik: bbaba (2003)]
Iva Rant -> [Ana Tratnik, Mateja Ilih, Iva Rant: aabbb (2015)]
Jana Antlej -> [Jana Antlej, Sonja Debeljak, Franci Rant: babab (2010), Gorazd Golob, Jana Antlej, Peter Golob: aaaba (2004)]
Jana Debeljak -> [Peter Mastnak, Jana Debeljak: babba (2000)]
Jana Ermenc -> [Jana Urh, Gorazd Savc, Jana Ermenc: abbbb (2007)]
Jana Golob -> [Jana Golob: aaaba (2015)]
Jana Hojnik -> [Jana Hojnik, Peter Ermenc, Sonja Rant: ababa (2008)]
Jana Ilih -> [Bojan Cotman, Jana Ilih, Hinko Zorc: aaaba (2016), Urban Rant, Jana Ilih: abbaa (2016)]
Jana Leban -> [Jana Leban: aaaaa (2015), Cvetko Zorc, Jana Leban, Eva Fajdiga: baaba (2009), Peter Antlej, Jana Leban, Zoran Fajdiga: abbbb (2005)]
Jana Oblak -> [Jana Oblak, Peter Leban, Lojze Zorc: bbbab (2016)]
Jana Rant -> [Hinko Kotnik, Jana Rant: babaa (2015), Jana Rant, Bojan Cotman: bbbab (2008)]
Jana Rant -> [Jana Rant: aaaab (2002)]
Jana Urh -> [Jana Urh: bbaaa (2011), Jana Urh, Gorazd Savc, Jana Ermenc: abbbb (2007), Jana Urh, Zoran Oblak: bbaab (2004)]
Jana Veble -> [Jana Veble, Lojze Zorc, Cvetko Veble: abbbb (2002)]
Jana Zorc -> [Cvetko Antlej, Eva Bevc, Jana Zorc: aaabb (2000)]
Karel Debeljak -> [Karel Debeljak, Iva Bevc: bbabb (2000)]
Karel Ermenc -> [Roman Oblak, Karel Ermenc: aabba (2011)]
Karel Ermenc -> [Tone Urh, Urban Antlej, Karel Ermenc: bbbab (2012)]
Karel Golob -> [Tone Savc, Karel Golob: babbb (2016), Gorazd Antlej, Peter Zorc, Karel Golob: baaba (2010)]
Karel Leban -> [Gorazd Oblak, Karel Leban, Lojze Zorc: baaaa (2012)]
Karel Leban -> [Karel Leban, Ana Cotman: bbbaa (2007)]
Karel Oblak -> [Veronika Kotnik, Karel Oblak: aabaa (2008)]
Karel Rant -> [Karel Rant, Sonja Podobnik: aabab (2003)]
Karel Savc -> [Karel Savc, Eva Golob: aabab (2010)]
Karel Savc -> [Nina Ilih, Karel Savc: ababb (2004)]
Lojze Antlej -> [Lojze Antlej: babaa (2006)]
Lojze Antlej -> [Roman Urh, Lojze Antlej, Cvetko Kotnik: babba (2019)]
Lojze Antlej -> [Urban Veble, Lojze Antlej: bbabb (2008)]
Lojze Ermenc -> [Mateja Hojnik, Lojze Ermenc: bbbba (2013)]
Lojze Hojnik -> [Lojze Hojnik, Nina Savc, Peter Novak: babab (2012), Peter Veble, Lojze Hojnik, Tone Podobnik: babbb (2006)]
Lojze Kotnik -> [Peter Savc, Lojze Kotnik: ababa (2009)]
Lojze Mastnak -> [Lojze Mastnak, Olga Antlej: baabb (2005)]
Lojze Novak -> [Lojze Novak: aabbb (2003)]
Lojze Rant -> [Franci Zorc, Lojze Rant, Eva Leban: baaaa (2019), Lojze Rant: bbbaa (2002)]
Lojze Rant -> [Hinko Veble, Roman Urh, Lojze Rant: abbba (2015)]
Lojze Zorc -> [Gorazd Oblak, Karel Leban, Lojze Zorc: baaaa (2012), Lojze Zorc, Gorazd Hojnik, Cvetko Novak: abaaa (2005)]
Lojze Zorc -> [Jana Oblak, Peter Leban, Lojze Zorc: bbbab (2016)]
Lojze Zorc -> [Lojze Zorc, Tone Mastnak: aaaaa (2006)]
Lojze Zorc -> [Lojze Zorc: bbbbb (2016), Jana Veble, Lojze Zorc, Cvetko Veble: abbbb (2002)]
Mateja Bevc -> [Mateja Bevc, Cvetko Tratnik, Zoran Fajdiga: babaa (2012), Mateja Bevc, Mateja Hojnik, Nina Debeljak: aabba (2000)]
Mateja Hojnik -> [Mateja Bevc, Mateja Hojnik, Nina Debeljak: aabba (2000)]
Mateja Hojnik -> [Mateja Hojnik, Lojze Ermenc: bbbba (2013)]
Mateja Ilih -> [Ana Tratnik, Mateja Ilih, Iva Rant: aabbb (2015), Mateja Ilih, Draga Golob: baaaa (2007)]
Mateja Ilih -> [Mateja Ilih, Franci Debeljak, Olga Veble: babab (2011)]
Mateja Leban -> [Mateja Leban, Franci Hojnik, Peter Veble: bbbaa (2001)]
Mateja Oblak -> [Mateja Oblak: aabaa (2011)]
Mateja Tratnik -> [Mateja Tratnik: abbaa (2007)]
Nina Debeljak -> [Eva Bevc, Nina Debeljak: bbabb (2010), Urban Podobnik, Nina Debeljak, Ana Veble: bbbaa (2005), Mateja Bevc, Mateja Hojnik, Nina Debeljak: aabba (2000)]
Nina Ermenc -> [Veronika Bevc, Nina Ermenc: abaaa (2007)]
Nina Hojnik -> [Eva Novak, Nina Hojnik: bbaaa (2018), Nina Hojnik, Draga Savc: bbbba (2013)]
Nina Ilih -> [Nina Ilih, Karel Savc: ababb (2004)]
Nina Leban -> [Ana Tratnik, Eva Cotman, Nina Leban: bbbaa (2007)]
Nina Novak -> [Gorazd Savc, Nina Novak, Veronika Novak: bbaab (2011)]
Nina Savc -> [Lojze Hojnik, Nina Savc, Peter Novak: babab (2012)]
Nina Tratnik -> [Franci Ermenc, Nina Tratnik, Olga Jelen: abbbb (2001)]
Nina Veble -> [Nina Veble: aaabb (2010)]
Nina Zorc -> [Eva Novak, Nina Zorc: abaab (2014)]
Olga Antlej -> [Lojze Mastnak, Olga Antlej: baabb (2005)]
Olga Fajdiga -> [Olga Fajdiga: baaba (2002)]
Olga Hojnik -> [Ana Ermenc, Olga Hojnik, Zoran Novak: abbba (2002)]
Olga Ilih -> [Gorazd Oblak, Gorazd Antlej, Olga Ilih: aabba (2011), Eva Oblak, Peter Zorc, Olga Ilih: babab (2004), Olga Ilih, Olga Ilih, Sonja Leban: abaaa (2001)]
Olga Ilih -> [Olga Ilih, Olga Ilih, Sonja Leban: abaaa (2001)]
Olga Jelen -> [Franci Ermenc, Nina Tratnik, Olga Jelen: abbbb (2001)]
Olga Leban -> [Olga Leban: abaab (2018)]
Olga Novak -> [Veronika Tratnik, Olga Novak, Zoran Novak: bbaab (2014), Franci Leban, Olga Novak: aabab (2009), Olga Novak, Hinko Golob: baabb (2003)]
Olga Oblak -> [Olga Oblak, Olga Zorc: ababa (2015)]
Olga Savc -> [Olga Savc, Peter Savc: bbbbb (2012)]
Olga Urh -> [Olga Urh: bbaba (2007)]
Olga Veble -> [Mateja Ilih, Franci Debeljak, Olga Veble: babab (2011)]
Olga Veble -> [Sonja Bevc, Gorazd Podobnik, Olga Veble: bbaaa (2001)]
Olga Zorc -> [Olga Oblak, Olga Zorc: ababa (2015), Olga Zorc: bbabb (2005)]
Peter Antlej -> [Peter Antlej, Jana Leban, Zoran Fajdiga: abbbb (2005)]
Peter Cotman -> [Peter Cotman: bbaab (2018)]
Peter Ermenc -> [Jana Hojnik, Peter Ermenc, Sonja Rant: ababa (2008)]
Peter Golob -> [Gorazd Golob, Jana Antlej, Peter Golob: aaaba (2004), Peter Golob, Eva Ilih, Cvetko Rant: bbbbb (2003)]
Peter Hojnik -> [Peter Hojnik, Eva Novak: baabb (2019), Peter Hojnik, Cvetko Mastnak, Bojan Podobnik: abbaa (2011)]
Peter Hojnik -> [Peter Hojnik: aabba (2019)]
Peter Leban -> [Jana Oblak, Peter Leban, Lojze Zorc: bbbab (2016)]
Peter Leban -> [Peter Leban, Cvetko Rant: babba (2000)]
Peter Leban -> [Peter Leban, Zoran Novak: ababa (2004)]
Peter Mastnak -> [Zoran Golob, Veronika Kotnik, Peter Mastnak: aaaab (2003), Peter Mastnak, Jana Debeljak: babba (2000)]
Peter Novak -> [Peter Novak, Veronika Podobnik: babaa (2018), Lojze Hojnik, Nina Savc, Peter Novak: babab (2012)]
Peter Savc -> [Olga Savc, Peter Savc: bbbbb (2012), Peter Savc, Lojze Kotnik: ababa (2009)]
Peter Veble -> [Peter Veble, Lojze Hojnik, Tone Podobnik: babbb (2006), Mateja Leban, Franci Hojnik, Peter Veble: bbbaa (2001)]
Peter Veble -> [Peter Veble, Tone Podobnik, Hinko Savc: abbba (2005), Peter Veble: bbbab (2002)]
Peter Veble -> [Peter Veble, Urban Debeljak: aaaab (2000)]
Peter Zorc -> [Gorazd Antlej, Peter Zorc, Karel Golob: baaba (2010), Eva Oblak, Peter Zorc, Olga Ilih: babab (2004)]
Roman Hojnik -> [Roman Urh, Roman Hojnik: aabaa (2010)]
Roman Leban -> [Draga Fajdiga, Roman Leban, Eva Kotnik: aaaab (2005)]
Roman Leban -> [Roman Leban, Gorazd Novak: bbabb (2015), Roman Leban, Gorazd Urh, Sonja Veble: abbab (2003)]
Roman Oblak -> [Roman Oblak, Karel Ermenc: aabba (2011), Urban Ilih, Bojan Tratnik, Roman Oblak: babba (2002)]
Roman Savc -> [Roman Savc: babab (2005)]
Roman Urh -> [Roman Urh, Lojze Antlej, Cvetko Kotnik: babba (2019), Roman Urh, Eva Oblak, Tone Tratnik: aabbb (2016), Hinko Veble, Roman Urh, Lojze Rant: abbba (2015), Roman Urh, Roman Hojnik: aabaa (2010)]
Sonja Bevc -> [Sonja Bevc, Ana Ilih, Hinko Oblak: baaba (2014)]
Sonja Bevc -> [Sonja Bevc, Gorazd Podobnik, Olga Veble: bbaaa (2001)]
Sonja Debeljak -> [Jana Antlej, Sonja Debeljak, Franci Rant: babab (2010)]
Sonja Ermenc -> [Sonja Ermenc: aabab (2019)]
Sonja Golob -> [Urban Cotman, Sonja Golob, Urban Rant: aabaa (2015)]
Sonja Leban -> [Sonja Leban, Tone Urh, Tone Antlej: bbbab (2006), Olga Ilih, Olga Ilih, Sonja Leban: abaaa (2001)]
Sonja Podobnik -> [Karel Rant, Sonja Podobnik: aabab (2003)]
Sonja Podobnik -> [Sonja Podobnik: bbbbb (2009)]
Sonja Rant -> [Jana Hojnik, Peter Ermenc, Sonja Rant: ababa (2008)]
Sonja Savc -> [Hinko Debeljak, Gorazd Oblak, Sonja Savc: babaa (2005)]
Sonja Urh -> [Sonja Urh: aabbb (2010), Sonja Urh, Zoran Novak, Cvetko Mastnak: baaba (2010)]
Sonja Veble -> [Sonja Veble: bbbab (2019), Veronika Zorc, Sonja Veble, Hinko Zorc: bbaba (2016), Roman Leban, Gorazd Urh, Sonja Veble: abbab (2003)]
Sonja Zorc -> [Gorazd Podobnik, Sonja Zorc: abbaa (2014)]
Tone Antlej -> [Sonja Leban, Tone Urh, Tone Antlej: bbbab (2006)]
Tone Bevc -> [Bojan Urh, Gorazd Podobnik, Tone Bevc: abbbb (2018)]
Tone Fajdiga -> [Tone Fajdiga, Bojan Novak, Urban Bevc: abbaa (2012)]
Tone Hojnik -> [Tone Hojnik, Zoran Novak: abbbb (2017)]
Tone Jelen -> [Ana Golob, Tone Jelen: bbbaa (2005)]
Tone Jelen -> [Cvetko Leban, Tone Jelen: aaabb (2007)]
Tone Mastnak -> [Lojze Zorc, Tone Mastnak: aaaaa (2006)]
Tone Mastnak -> [Tone Mastnak: bbbbb (2004)]
Tone Mastnak -> [Veronika Novak, Tone Mastnak, Franci Bevc: abaaa (2005)]
Tone Novak -> [Tone Oblak, Tone Novak: bbabb (2011)]
Tone Oblak -> [Tone Oblak, Tone Novak: bbabb (2011), Tone Oblak: bbaaa (2004)]
Tone Podobnik -> [Tone Podobnik, Gorazd Novak: aaabb (2006), Peter Veble, Lojze Hojnik, Tone Podobnik: babbb (2006), Peter Veble, Tone Podobnik, Hinko Savc: abbba (2005)]
Tone Savc -> [Tone Savc, Karel Golob: babbb (2016), Tone Savc: bbbba (2004)]
Tone Savc -> [Veronika Mastnak, Veronika Bevc, Tone Savc: baaaa (2019), Franci Bevc, Tone Savc: ababb (2006)]
Tone Tratnik -> [Gorazd Golob, Tone Tratnik: bbbab (2012), Urban Veble, Tone Tratnik: abbbb (2002)]
Tone Tratnik -> [Roman Urh, Eva Oblak, Tone Tratnik: aabbb (2016)]
Tone Urh -> [Sonja Leban, Tone Urh, Tone Antlej: bbbab (2006), Tone Urh: babab (2002)]
Tone Urh -> [Tone Urh, Urban Antlej, Karel Ermenc: bbbab (2012)]
Tone Veble -> [Tone Veble, Eva Golob, Cvetko Tratnik: aabab (2014)]
Urban Antlej -> [Tone Urh, Urban Antlej, Karel Ermenc: bbbab (2012)]
Urban Bevc -> [Tone Fajdiga, Bojan Novak, Urban Bevc: abbaa (2012)]
Urban Cotman -> [Urban Cotman, Sonja Golob, Urban Rant: aabaa (2015)]
Urban Debeljak -> [Peter Veble, Urban Debeljak: aaaab (2000)]
Urban Ilih -> [Urban Ilih, Bojan Tratnik, Roman Oblak: babba (2002)]
Urban Leban -> [Urban Leban, Gorazd Oblak, Zoran Mastnak: aabab (2005)]
Urban Oblak -> [Urban Oblak: bbbba (2008)]
Urban Podobnik -> [Gorazd Tratnik, Urban Podobnik, Zoran Fajdiga: baaba (2014), Urban Podobnik, Nina Debeljak, Ana Veble: bbbaa (2005)]
Urban Rant -> [Urban Rant, Jana Ilih: abbaa (2016), Urban Cotman, Sonja Golob, Urban Rant: aabaa (2015), Urban Rant: baaab (2012)]
Urban Veble -> [Urban Veble, Lojze Antlej: bbabb (2008)]
Urban Veble -> [Urban Veble: aabba (2002), Urban Veble, Tone Tratnik: abbbb (2002)]
Veronika Bevc -> [Veronika Mastnak, Veronika Bevc, Tone Savc: baaaa (2019), Veronika Bevc, Nina Ermenc: abaaa (2007)]
Veronika Debeljak -> [Veronika Debeljak, Ana Zorc: ababa (2003)]
Veronika Fajdiga -> [Veronika Fajdiga: abbbb (2003), Ana Zorc, Eva Golob, Veronika Fajdiga: babaa (2002)]
Veronika Hojnik -> [Veronika Hojnik, Ana Zorc, Ana Jelen: aaaba (2015)]
Veronika Ilih -> [Veronika Ilih: aabbb (2014), Veronika Ilih: ababb (2004)]
Veronika Jelen -> [Veronika Jelen: bbaaa (2003)]
Veronika Kotnik -> [Gorazd Fajdiga, Veronika Kotnik: bbaba (2004)]
Veronika Kotnik -> [Veronika Kotnik, Zoran Novak: aaabb (2015), Veronika Kotnik, Karel Oblak: aabaa (2008), Zoran Golob, Veronika Kotnik, Peter Mastnak: aaaab (2003)]
Veronika Mastnak -> [Veronika Mastnak, Veronika Bevc, Tone Savc: baaaa (2019)]
Veronika Novak -> [Gorazd Savc, Nina Novak, Veronika Novak: bbaab (2011), Veronika Novak, Bojan Veble: baaba (2000)]
Veronika Novak -> [Veronika Novak, Tone Mastnak, Franci Bevc: abaaa (2005)]
Veronika Podobnik -> [Peter Novak, Veronika Podobnik: babaa (2018)]
Veronika Tratnik -> [Veronika Tratnik, Olga Novak, Zoran Novak: bbaab (2014)]
Veronika Tratnik -> [Veronika Tratnik: baaba (2011), Veronika Tratnik: abaaa (2005)]
Veronika Zorc -> [Bojan Leban, Hinko Veble, Veronika Zorc: abaab (2007)]
Veronika Zorc -> [Veronika Zorc, Sonja Veble, Hinko Zorc: bbaba (2016)]
Veronika Zorc -> [Veronika Zorc: aabba (2002)]
Zoran Antlej -> [Zoran Antlej: aaabb (2016)]
Zoran Debeljak -> [Zoran Debeljak, Draga Leban: bbbba (2003)]
Zoran Fajdiga -> [Gorazd Tratnik, Urban Podobnik, Zoran Fajdiga: baaba (2014), Mateja Bevc, Cvetko Tratnik, Zoran Fajdiga: babaa (2012), Hinko Kotnik, Hinko Leban, Zoran Fajdiga: baabb (2010), Peter Antlej, Jana Leban, Zoran Fajdiga: abbbb (2005)]
Zoran Golob -> [Zoran Golob, Hinko Debeljak: bbaba (2018), Zoran Golob, Veronika Kotnik, Peter Mastnak: aaaab (2003)]
Zoran Kotnik -> [Zoran Kotnik, Eva Veble: aabba (2009)]
Zoran Kotnik -> [Zoran Kotnik: bbbab (2005)]
Zoran Leban -> [Zoran Leban, Ana Ilih, Bojan Ilih: aabab (2019), Zoran Leban: babba (2010)]
Zoran Leban -> [Zoran Leban: abbab (2007)]
Zoran Mastnak -> [Zoran Mastnak: ababa (2017), Urban Leban, Gorazd Oblak, Zoran Mastnak: aabab (2005)]
Zoran Novak -> [Sonja Urh, Zoran Novak, Cvetko Mastnak: baaba (2010), Peter Leban, Zoran Novak: ababa (2004)]
Zoran Novak -> [Tone Hojnik, Zoran Novak: abbbb (2017), Veronika Kotnik, Zoran Novak: aaabb (2015), Veronika Tratnik, Olga Novak, Zoran Novak: bbaab (2014), Zoran Novak: bbbbb (2009), Ana Ermenc, Olga Hojnik, Zoran Novak: abbba (2002)]
Zoran Oblak -> [Jana Urh, Zoran Oblak: bbaab (2004)]
Zoran Urh -> [Zoran Urh: aabba (2015)]
Zoran Veble -> [Zoran Veble, Franci Ermenc: ababb (2005), Zoran Veble: aabab (2001)]
